//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\file02.oeynhausen.gneuss.de\global$\ServiceAuftragsTool\Archieve ähnelt.
        /// </summary>
        internal static string ArchievePfad {
            get {
                return ResourceManager.GetString("ArchievePfad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data Source=sql04;Initial catalog=Gneuss-GmbH;User ID=report;Password=nex852ICD;Connect Timeout=30;Encrypt=False ähnelt.
        /// </summary>
        internal static string Connectionstring {
            get {
                return ResourceManager.GetString("Connectionstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die SELECT TOP(100) PERCENT b.Mandant, b.Belegnummer, b.Belegdatum,b.Sprache, b.A0Empfaenger, b.A0Name1,o.Land,b.A0Land, b.A0PLZ, b.A0Ort,b.A0Strasse, b.USER_ProduktTyp, b.USER_Filternummer FROM dbo.KHKVKBelege AS b inner join obo_land_iso o on o.iso2 = A0Land WHERE(b.Belegkennzeichen IN(&apos;vvb&apos;)) AND(b.Mandant IN(2, 3)) AND b.Belegdatum &gt; getdate()-365 ORDER BY b.Belegnummer ähnelt.
        /// </summary>
        internal static string DB_Abfrage {
            get {
                return ResourceManager.GetString("DB_Abfrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10.228.4.9 ähnelt.
        /// </summary>
        internal static string IP_File02 {
            get {
                return ResourceManager.GetString("IP_File02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10.228.4.12 ähnelt.
        /// </summary>
        internal static string IP_SQL04 {
            get {
                return ResourceManager.GetString("IP_SQL04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\zellen_textboxen_mapping_internerBericht.json ähnelt.
        /// </summary>
        internal static string Path_CellMapping_InternerBericht {
            get {
                return ResourceManager.GetString("Path_CellMapping_InternerBericht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\zellen_textboxen_mapping_IBNP.json ähnelt.
        /// </summary>
        internal static string Path_CellMappingIBNP {
            get {
                return ResourceManager.GetString("Path_CellMappingIBNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\zellen_textboxen_mapping_IBNP_MRS.json ähnelt.
        /// </summary>
        internal static string Path_CellMappingIBNP_MRS {
            get {
                return ResourceManager.GetString("Path_CellMappingIBNP_MRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\zellen_textboxen_mapping_Serviceanforderungen.json ähnelt.
        /// </summary>
        internal static string Path_CellMappingServiceAnforderungen {
            get {
                return ResourceManager.GetString("Path_CellMappingServiceAnforderungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\zellen_textboxen_mapping_Stundennachweis.json ähnelt.
        /// </summary>
        internal static string Path_CellMappingStundenachweis {
            get {
                return ResourceManager.GetString("Path_CellMappingStundenachweis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\SprachenTabelleIBNP.json ähnelt.
        /// </summary>
        internal static string Path_LanguageJson_IBNP {
            get {
                return ResourceManager.GetString("Path_LanguageJson_IBNP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infos\SprachenTabelleIBNPMRS.json ähnelt.
        /// </summary>
        internal static string Path_LanguageJson_IBNP_MRS {
            get {
                return ResourceManager.GetString("Path_LanguageJson_IBNP_MRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\file02.oeynhausen.gneuss.de\global$\ServiceAuftragsTool\{0}\Anhaenge ähnelt.
        /// </summary>
        internal static string Pfad_Anhaenge_On {
            get {
                return ResourceManager.GetString("Pfad_Anhaenge_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ServiceTool\{0} ähnelt.
        /// </summary>
        internal static string Pfad_AuftragsOrdner_Off {
            get {
                return ResourceManager.GetString("Pfad_AuftragsOrdner_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\file02.oeynhausen.gneuss.de\global$\ServiceAuftragsTool\{0} ähnelt.
        /// </summary>
        internal static string Pfad_AuftragsOrdner_On {
            get {
                return ResourceManager.GetString("Pfad_AuftragsOrdner_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die \\file02.oeynhausen.gneuss.de\global$\ServiceAuftragsTool\{0}\Anhaenge\Unterschriften ähnelt.
        /// </summary>
        internal static string Pfad_Signatures_On {
            get {
                return ResourceManager.GetString("Pfad_Signatures_On", resourceCulture);
            }
        }
    }
}
